---
- name: include variables
  include_role:
    name: lihas_variables
  when: configspaces is not defined
- name: reset_apt_update
  set_fact:
    apt_update: False
- name: deploy /etc/network/interfaces
  template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
    mode: 0644
  when: hostvars[inventory_hostname].network.interfaces is defined
  register: result
- name: protect /etc/network/interfaces on Proxmox/LXC
  copy:
    dest: /etc/network/.pve-ignore.interfaces
    src: /dev/null
    mode: 0644
  when: ansible_virtualization_type == 'lxc' and hostvars[inventory_hostname].network.interfaces is defined
# repositories
- name: enable buster-backports
  template:
    src: etc/apt/sources.list.d/buster-backports.list
    dest: /etc/apt/sources.list.d/buster-backports.list
    mode: 0644
  register: result
- name: set_apt_update
  set_fact:
    apt_update: True
  when: result.changed
- name: create /etc/apt/preferences.d
  file:
    state: directory
    path: /etc/apt/preferences.d
    mode: 0755
- name: if wireguard is used, use from backports
  copy:
    src: etc/apt/preferences.d/wireguard.pref
    dest: /etc/apt/preferences.d/wireguard.pref
    mode: 0644
  register: result
- name: set_apt_update
  set_fact:
    apt_update: True
  when: result.changed
- name: apt update
  apt:
    update_cache: True
  when: apt_update
- name: reset_apt_update
  set_fact:
    apt_update: False
  when: apt_update
- name: install software
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - extrepo
    - rsync
    - screen
    - etckeeper
  loop_control:
    loop_var: item
- name: extrepo enable lihas
  command:
    cmd: /usr/bin/extrepo enable lihas
  changed_when: False
  register: result
- name: set_apt_update
  set_fact:
    apt_update: True
  when: '"repository already existed" not in result.stdout'
- name: apt update
  apt:
    update_cache: True
  when: apt_update
- name: reset_apt_update
  set_fact:
    apt_update: False
  when: apt_update
- name: Update apt cache
  apt:
    update_cache: True
    cache_valid_time: 600
- name: disable systemd-modules-load.service on lxc
  systemd:
    name: systemd-modules-load.service
    masked: true
  when: ansible_virtualization_type == 'lxc'
- name: disable systemd-journald-audit.socket on lxc
  systemd:
    name: systemd-journald-audit.socket
    masked: true
  when: ansible_virtualization_type == 'lxc'
- name: disable sys-kernel-config.mount on lxc
  systemd:
    name: sys-kernel-config.mount
    masked: true
  when: ansible_virtualization_type == 'lxc'
- name: disable sys-kernel-debug.mount on lxc
  systemd:
    name: sys-kernel-debug.mount
    masked: true
  when: ansible_virtualization_type == 'lxc'
- name: Set default locale to de_DE.UTF-8
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: de_DE.UTF-8
    vtype: select
- name: Set to generate locales
  debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: en_US.UTF-8 UTF-8, de_DE.UTF-8 UTF-8
    vtype: multiselect
- name: mark role lihas_common done
  set_fact:
    role_done_lihas_common: true
  when: role_done_lihas_common is not defined


# - debug:
#     var: hostvars
