---
- name: reset_apt_update
  set_fact:
    apt_update: False
- name: deploy /etc/network/interfaces
  template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
  when: hostvars[inventory_hostname].network.interfaces is defined
  register: result
- name: protect /etc/network/interfaces on Proxmox/LXC
  file:
    path: /etc/network/.pve-ignore.interfaces
    state: touch
  when: ansible_virtualization_type == 'lxc' and hostvars[inventory_hostname].network.interfaces is defined
# repositories
- name: enable buster-backports
  template:
    src: etc/apt/sources.list.d/buster-backports.list
    dest: /etc/apt/sources.list.d/buster-backports.list
  register: result
- name: set_apt_update
  set_fact:
    apt_update: True
  when: result.changed == True
- name: create /etc/apt/preferences.d
  file:
    state: directory
    path: /etc/apt/preferences.d
- name: if wireguard is used, use from backports
  copy:
    src: etc/apt/preferences.d/wireguard.pref
    dest: /etc/apt/preferences.d/wireguard.pref
  register: result
- name: set_apt_update
  set_fact:
    apt_update: True
  when: result.changed == True
- name: apt update
  apt:
    update_cache: True
  when: apt_update == True
- name: reset_apt_update
  set_fact:
    apt_update: False
  when: apt_update == True
- name: install software
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - extrepo
    - rsync
    - screen
  loop_control:
    loop_var: item
- name: extrepo enable lihas
  command:
    cmd: /usr/bin/extrepo enable lihas
  changed_when: False
  register: result
- name: set_apt_update
  set_fact:
    apt_update: True
  when: '"Configuration enabled" in result.stdout'
- name: apt update
  apt:
    update_cache: True
  when: apt_update == True
- name: reset_apt_update
  set_fact:
    apt_update: False
  when: apt_update == True
- apt:
    update_cache: True
    cache_valid_time: 600

# - debug:
#     var: hostvars
